chore: Add deployment of static assets action
cloudscape-design/.github pull request #36
Opened 2023-02-06 13:45 UTC by michaeldowseza

*Description of changes:*
Adds a reusable workflow to deploy a github artifact that was create by the build-lint-test workflow

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-06 14:14 UTC, timogasda requested changes

2023-02-06 14:14 UTC, timogasda commented on .github/actions/download-artifact/action.yml
> +    description: "A file, directory or wildcard pattern that describes what to upload"
You mean what to *download*?

2023-02-06 14:14 UTC, timogasda commented on .github/workflows/deploy.yml
> +        uses: chrnorm/deployment-action@v2.0.1
👀

2023-02-06 15:18 UTC, michaeldowseza commented on .github/actions/download-artifact/action.yml
> +    description: "A file, directory or wildcard pattern that describes what to upload"
Fixed.

2023-02-08 10:50 UTC, michaeldowseza commented on .github/workflows/deploy.yml
> +        uses: chrnorm/deployment-action@v2.0.1
Removed third party action

2023-02-08 12:16 UTC, timogasda approved these changes

2023-02-08 12:17 UTC, merged